appId: com.priyansh.mala
---
- launchApp
- assertVisible:
    id: settingsButton
- tapOn:
    id: settingsButton
- assertVisible:
    id: malaStyleRow
- tapOn:
    id: malaStyleRow
- assertVisible:
    id: malaApplyButton
