appId: com.priyansh.mala
---
- launchApp:
    clearState: true
- tapOn:
    id: introBegin
- tapOn:
    id: settingsButton
- assertVisible:
    id: malaStyleRow
- tapOn:
    id: malaStyleRow
- assertVisible:
    id: malaApplyButton
